version: '3.8'

services:
  core:
    build:
      context: .
      dockerfile: ./docfiles/service/Dockerfile
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - db
  
  db:
    build:
      context: .
      dockerfile: ./docfiles/database/Dockerfile
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weather_db
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  pgAdmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5555:80"
    depends_on:
      - db

volumes:
  db-data:
